version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "user_management"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "3LdNmrGS"
    ports:
      - "5432:5432"
  server:
    build: .
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "3LdNmrGS"
      POSTGRES_HOST: "postgres"
    restart: always
    links:
      - "db:postgres"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0
